--- @meta _

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/live/Interface/AddOns/Blizzard_PlayerChoice/Blizzard_PlayerChoiceCypherOptionTemplate.xml#L4)
--- Template
--- @class PlayerChoiceCypherOptionTemplate : Frame, PlayerChoicePowerChoiceTemplate, PlayerChoiceCypherOptionTemplateMixin
--- @field minOptionHeight number # 343
--- @field Header PlayerChoiceCypherOptionTemplate_Header
--- @field Background Texture
--- @field RarityGlow Texture
--- @field ArtworkGlow Texture
--- @field ArtworkSparkles Texture
--- @field Glow Texture
--- @field Pixels1 Texture
--- @field Pixels2 Texture
--- @field Wisps Texture
--- @field Wisps2 Texture
--- @field Glow2 Texture
--- @field LineGlow Texture
--- @field LineGlowMask MaskTexture
--- @field BottomMask MaskTexture

