--- @meta _

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/ptr2/Interface/AddOns/Blizzard_UIWidgets/Mainline/Blizzard_UIWidgetTemplateTextureWithAnimation.xml#L3)
--- Template
--- @class UIWidgetTemplateTextureWithAnimation : Frame, UIWidgetBaseTemplate, UIWidgetTemplateTextureWithAnimationMixin
--- @field defaultTooltipAnchor string # "ANCHOR_BOTTOM"
--- @field BackgroundGlow Texture
--- @field BorderGlow1 Texture
--- @field BorderGlow2 Texture
--- @field Background Texture
--- @field BorderGlow3 Texture
--- @field TransitionGlow2 Texture
--- @field TransitionGlow3 Texture
--- @field CenterEffect1 Texture
--- @field CenterEffect2 Texture
--- @field CenterEffect5 Texture
--- @field CenterEffect3 Texture
--- @field CenterEffect4 Texture
--- @field Border Texture
--- @field TransitionGlow Texture
--- @field BorderGlow4 Texture
--- @field CenterEffect1Anim UIWidgetTemplateTextureWithAnimation_CenterEffect1Anim
--- @field CenterEffect2Anim UIWidgetTemplateTextureWithAnimation_CenterEffect2Anim
--- @field CenterEffect4GlowAnim UIWidgetTemplateTextureWithAnimation_CenterEffect4GlowAnim
--- @field CenterEffect5Anim UIWidgetTemplateTextureWithAnimation_CenterEffect5Anim
--- @field TransitionGlowAnim UIWidgetTemplateTextureWithAnimation_TransitionGlowAnim
--- @field BorderGlow1Anim UIWidgetTemplateTextureWithAnimation_BorderGlow1Anim
--- @field BorderGlow2Anim UIWidgetTemplateTextureWithAnimation_BorderGlow2Anim
--- @field BorderGlow3Anim UIWidgetTemplateTextureWithAnimation_BorderGlow3Anim
--- @field BorderGlow4Anim UIWidgetTemplateTextureWithAnimation_BorderGlow4Anim

