--- @meta _

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/beta/Interface/AddOns/Blizzard_UIWidgets/Mainline/Blizzard_UIWidgetTemplateCaptureBar.xml#L3)
--- Template
--- @class UIWidgetTemplateCaptureBar : Frame, UIWidgetBaseTemplate, UIWidgetTemplateCaptureBarMixin
--- @field LeftBar Texture
--- @field LeftBarShadow Texture
--- @field RightBar Texture
--- @field RightBarShadow Texture
--- @field Bar Texture
--- @field NeutralBar Texture
--- @field BarBackground Texture
--- @field RightLine Texture
--- @field LeftLine Texture
--- @field Divider Texture
--- @field Spark Texture
--- @field Glow1 Texture
--- @field Glow2 Texture
--- @field Glow3 Texture
--- @field LeftArrow Texture
--- @field RightArrow Texture
--- @field SparkNeutral Texture
--- @field LeftArrowAnim UIWidgetTemplateCaptureBar_LeftArrowAnim
--- @field RightArrowAnim UIWidgetTemplateCaptureBar_RightArrowAnim
--- @field GlowPulseAnim UIWidgetTemplateCaptureBar_GlowPulseAnim

