--- @meta _

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/ptr/Interface/AddOns/Blizzard_ProfessionsCustomerOrders/Blizzard_ProfessionsCustomerOrdersForm.xml#L5)
--- Template
--- @class ProfessionsCustomerListingsElementTemplate : Button, ProfessionsCustomerListingsElementMixin
--- @field HighlightTexture Texture

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/ptr/Interface/AddOns/Blizzard_ProfessionsCustomerOrders/Blizzard_ProfessionsCustomerOrdersForm.xml#L18)
--- Template
--- @class ProfessionsCustomerOrderFormTemplate : Frame, ProfessionsCustomerOrderFormMixin
--- @field LeftPanelBackground ProfessionsCustomerOrderFormTemplate_LeftPanelBackground
--- @field RightPanelBackground ProfessionsCustomerOrderFormTemplate_RightPanelBackground
--- @field BackButton ProfessionsCustomerOrderFormTemplate_BackButton
--- @field FavoriteButton ProfessionsCustomerOrderFormTemplate_FavoriteButton
--- @field OutputIcon ProfessionsCustomerOrderFormTemplate_OutputIcon
--- @field MinimumQuality ProfessionsCustomerOrderFormTemplate_MinimumQuality
--- @field OrderRecipientDropdown ProfessionsCustomerOrderFormTemplate_OrderRecipientDropdown
--- @field OrderRecipientTarget ProfessionsCustomerOrderFormTemplate_OrderRecipientTarget
--- @field OrderRecipientDisplay ProfessionsCustomerOrderFormTemplate_OrderRecipientDisplay
--- @field RecraftSlot ProfessionsCustomerOrderFormTemplate_RecraftSlot
--- @field ReagentContainer ProfessionsCustomerOrderFormTemplate_ReagentContainer
--- @field PaymentContainer ProfessionsCustomerOrderFormTemplate_PaymentContainer
--- @field TrackRecipeCheckbox ProfessionsCustomerOrderFormTemplate_TrackRecipeCheckbox
--- @field AllocateBestQualityCheckbox ProfessionsCustomerOrderFormTemplate_AllocateBestQualityCheckbox
--- @field QualityDialog ProfessionsCustomerOrderFormTemplate_QualityDialog
--- @field CurrentListings ProfessionsCustomerOrderFormTemplate_CurrentListings
--- @field RecipeHeader Texture
--- @field RecipeName ProfessionsCustomerOrderFormTemplate_RecipeName
--- @field RecraftRecipeName ProfessionsCustomerOrderFormTemplate_RecraftRecipeName
--- @field ProfessionText ProfessionsCustomerOrderFormTemplate_ProfessionText
--- @field OrderStateText ProfessionsCustomerOrderFormTemplate_OrderStateText
--- @field MinimumQualityIcon Texture

