--- @meta _

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/live/Interface/AddOns/Blizzard_PlayerSpells/ClassSpecializations/Blizzard_ClassSpecializationsFrame.xml#L5)
--- Template
--- @class ClassSpecSpellTemplate : Button, ClassSpecSpellMixin
--- @field Ring Texture
--- @field Icon Texture

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/live/Interface/AddOns/Blizzard_PlayerSpells/ClassSpecializations/Blizzard_ClassSpecializationsFrame.xml#L32)
--- Template
--- @class ClassSpecFrameTemplate : Frame, HorizontalLayoutFrame, ClassSpecFrameMixin
--- @field disabledOverlayAlpha number # 0.8
--- @field DisabledOverlay ClassSpecFrameTemplate_DisabledOverlay
--- @field BlackBG Texture
--- @field Background Texture

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/live/Interface/AddOns/Blizzard_PlayerSpells/ClassSpecializations/Blizzard_ClassSpecializationsFrame.xml#L65)
--- Template
--- @class ClassSpecContentFrameTemplate : Frame, ClassSpecContentFrameMixin
--- @field expand boolean # true
--- @field ActivateButton ClassSpecContentFrameTemplate_ActivateButton
--- @field AnimationHolder ClassSpecContentFrameTemplate_AnimationHolder
--- @field HoverBackground Texture
--- @field SpecImageBorderOff Texture
--- @field HoverSpecImageBorder Texture
--- @field SpecImageBorderOn Texture
--- @field ActivatedSpecImageBorder Texture
--- @field SpecImage Texture
--- @field HoverSpecImage Texture
--- @field ActivatedSpecImage Texture
--- @field SpecName ClassSpecContentFrameTemplate_SpecName
--- @field RoleIcon Texture
--- @field RoleName ClassSpecContentFrameTemplate_RoleName
--- @field Description ClassSpecContentFrameTemplate_Description
--- @field SampleAbilityText ClassSpecContentFrameTemplate_SampleAbilityText
--- @field ActivatedText ClassSpecContentFrameTemplate_ActivatedText
--- @field Separator Texture
--- @field ColumnDivider Texture
--- @field ActivatedBackgroundBack1 Texture
--- @field ActivatedBackgroundBack2 Texture
--- @field ActivatedBackgroundLeft1 Texture
--- @field ActivatedBackgroundLeft2 Texture
--- @field ActivatedBackgroundLeft3 Texture
--- @field ActivatedBackgroundLeft4 Texture
--- @field ActivatedBackgroundRight1 Texture
--- @field ActivatedBackgroundRight2 Texture
--- @field ActivatedBackgroundRight3 Texture
--- @field ActivatedBackgroundRight4 Texture
--- @field ActivationFlashBGBack1 Texture
--- @field ActivationFlashBGBack2 Texture
--- @field ActivationFlashBGLeft1 Texture
--- @field ActivationFlashBGLeft2 Texture
--- @field ActivationFlashBGLeft3 Texture
--- @field ActivationFlashBGLeft4 Texture
--- @field ActivationFlashBGRight1 Texture
--- @field ActivationFlashBGRight2 Texture
--- @field ActivationFlashBGRight3 Texture
--- @field ActivationFlashBGRight4 Texture
--- @field ActivationExpandFx Texture
--- @field ActivationExpandFxMask MaskTexture
--- @field ActivationExpandFxMask2 MaskTexture

