--- @meta _

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/live/Interface/AddOns/Blizzard_PlayerSpells/ClassTalents/Blizzard_ClassTalentsFrame.xml#L5)
--- Template
--- @class ClassTalentCurrencyDisplayTemplate : Frame, ResizeLayoutFrame, ClassTalentCurrencyDisplayMixin
--- @field CurrencyLabel ClassTalentCurrencyDisplayTemplate_CurrencyLabel
--- @field CurrencyAmount ClassTalentCurrencyDisplayTemplate_CurrencyAmount

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/live/Interface/AddOns/Blizzard_PlayerSpells/ClassTalents/Blizzard_ClassTalentsFrame.xml#L19)
--- Template
--- @class ClassTalentsFrameTemplate : Frame, TalentFrameBaseTemplate, ClassTalentsFrameMixin
--- @field getTemplateType any # ClassTalentUtil.GetTemplateForTalentType
--- @field HeroTalentsContainer ClassTalentsFrameTemplate_HeroTalentsContainer
--- @field ClassCurrencyDisplay ClassTalentsFrameTemplate_ClassCurrencyDisplay
--- @field SpecCurrencyDisplay ClassTalentsFrameTemplate_SpecCurrencyDisplay
--- @field LoadSystem ClassTalentsFrameTemplate_LoadSystem
--- @field SearchBox ClassTalentsFrameTemplate_SearchBox
--- @field SearchPreviewContainer ClassTalentsFrameTemplate_SearchPreviewContainer
--- @field ApplyButton ClassTalentsFrameTemplate_ApplyButton
--- @field InspectCopyButton ClassTalentsFrameTemplate_InspectCopyButton
--- @field ResetButton ClassTalentsFrameTemplate_ResetButton
--- @field UndoButton ClassTalentsFrameTemplate_UndoButton
--- @field WarmodeButton ClassTalentsFrameTemplate_WarmodeButton
--- @field PvPTalentSlotTray ClassTalentsFrameTemplate_PvPTalentSlotTray
--- @field PvPTalentList ClassTalentsFrameTemplate_PvPTalentList
--- @field FxModelScene ClassTalentsFrameTemplate_FxModelScene
--- @field BlackBG Texture
--- @field BottomBar Texture
--- @field Background Texture
--- @field OverlayBackgroundRight Texture
--- @field OverlayBackgroundRightMask MaskTexture
--- @field OverlayBackgroundMid Texture
--- @field OverlayBackgroundMidMask MaskTexture
--- @field Clouds1 Texture
--- @field Clouds2 Texture
--- @field AirParticlesClose Texture
--- @field AirParticlesFar Texture
--- @field ActivationExpandFx Texture
--- @field ActivationExpandFxMask MaskTexture
--- @field ActivationClassFx Texture
--- @field ActivationClassFx2 Texture
--- @field ActivationClassFx3 Texture
--- @field ActivationClassFx4 Texture
--- @field ActivationTitansFX Texture
--- @field FullMask MaskTexture

