--- @meta _

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/ptr/Interface/AddOns/Blizzard_PlayerSpells/ClassTalents/Blizzard_HeroTalentsContainer.xml#L5)
--- Template
--- @class HeroTalentsTreeContainerTemplate : Frame

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/ptr/Interface/AddOns/Blizzard_PlayerSpells/ClassTalents/Blizzard_HeroTalentsContainer.xml#L11)
--- Template
--- @class HeroTalentsTreeNodesContainerTemplate : Frame

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/ptr/Interface/AddOns/Blizzard_PlayerSpells/ClassTalents/Blizzard_HeroTalentsContainer.xml#L17)
--- Template
--- @class HeroTalentSpecButtonTemplate : Button, HeroSpecButtonMixin
--- @field SearchIcon HeroTalentSpecButtonTemplate_SearchIcon
--- @field ChoiceBackground Texture
--- @field ChoiceBackground2 Texture
--- @field Icon1 Texture
--- @field Icon2 Texture
--- @field Icon1Hover Texture
--- @field Icon2Hover Texture
--- @field Icon1Anim Texture
--- @field HeroClassIconSheen HeroTalentSpecButtonTemplate_HeroClassIconSheen
--- @field HeroClassIconSheenMask MaskTexture
--- @field IconMask MaskTexture
--- @field Icon1SplitMask MaskTexture
--- @field Icon2SplitMask MaskTexture
--- @field Border Texture
--- @field ChoiceBorder Texture
--- @field BorderHover Texture
--- @field ChoiceBorderHover Texture
--- @field LockedOverlay Texture
--- @field HeroClassRingBorderSheen HeroTalentSpecButtonTemplate_HeroClassRingBorderSheen
--- @field HeroClassRingBorderSheenMask MaskTexture
--- @field ChoiceGlowAnim HeroTalentSpecButtonTemplate_ChoiceGlowAnim
--- @field HeroClassPassiveAnim HeroTalentSpecButtonTemplate_HeroClassPassiveAnim

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/ptr/Interface/AddOns/Blizzard_PlayerSpells/ClassTalents/Blizzard_HeroTalentsContainer.xml#L181)
--- Template
--- @class HeroTalentsContainerTemplate : Frame, HeroTalentsContainerMixin
--- @field helpTipOffsetX number # -10
--- @field HeroSpecButton HeroTalentsContainerTemplate_HeroSpecButton
--- @field CurrencyFrame HeroTalentsContainerTemplate_CurrencyFrame
--- @field CollapseButton HeroTalentsContainerTemplate_CollapseButton
--- @field PreviewContainer HeroTalentsContainerTemplate_PreviewContainer
--- @field ExpandedContainer HeroTalentsContainerTemplate_ExpandedContainer
--- @field CollapsedContainer HeroTalentsContainerTemplate_CollapsedContainer
--- @field HeroSpecLabel HeroTalentsContainerTemplate_HeroSpecLabel
--- @field ChooseSpecLabel1 HeroTalentsContainerTemplate_ChooseSpecLabel1
--- @field ChooseSpecLabel2 HeroTalentsContainerTemplate_ChooseSpecLabel2
--- @field LockedLabel1 HeroTalentsContainerTemplate_LockedLabel1
--- @field LockedLabel2 HeroTalentsContainerTemplate_LockedLabel2

