--- @meta _

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/live/Interface/AddOns/Blizzard_Professions/Blizzard_ProfessionsSpecializations.xml#L5)
--- Template
--- @class ProfessionsSpecPageTemplate : Frame, TalentFrameBaseTemplate, ProfessionsSpecFrameMixin
--- @field enableZoomAndPan boolean # false
--- @field PanelFooter ProfessionsSpecPageTemplate_PanelFooter
--- @field ApplyButton ProfessionsSpecPageTemplate_ApplyButton
--- @field UnlockTabButton ProfessionsSpecPageTemplate_UnlockTabButton
--- @field ViewTreeButton ProfessionsSpecPageTemplate_ViewTreeButton
--- @field BackToPreviewButton ProfessionsSpecPageTemplate_BackToPreviewButton
--- @field ViewPreviewButton ProfessionsSpecPageTemplate_ViewPreviewButton
--- @field BackToFullTreeButton ProfessionsSpecPageTemplate_BackToFullTreeButton
--- @field UndoButton ProfessionsSpecPageTemplate_UndoButton
--- @field TreeView ProfessionsSpecPageTemplate_TreeView
--- @field DetailedView ProfessionsSpecPageTemplate_DetailedView
--- @field VerticalDivider ProfessionsSpecPageTemplate_VerticalDivider
--- @field TopDivider ProfessionsSpecPageTemplate_TopDivider
--- @field TreePreview ProfessionsSpecPageTemplate_TreePreview
--- @field FxModelScene ProfessionsSpecPageTemplate_FxModelScene

