--- @meta _

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/ptr/Interface/AddOns/Blizzard_PartyPoseUI/Blizzard_PartyPoseUI.xml#L3)
--- Template
--- @class PartyPoseRewardsButtonTemplate : Button, PartyPoseRewardsMixin
--- @field NameFrame Texture
--- @field Icon Texture
--- @field IconOverlay Texture
--- @field IconBorder Texture
--- @field Name PartyPoseRewardsButtonTemplate_Name
--- @field Count PartyPoseRewardsButtonTemplate_Count
--- @field Label PartyPoseRewardsButtonTemplate_Label
--- @field AnimFade PartyPoseRewardsButtonTemplate_AnimFade

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/ptr/Interface/AddOns/Blizzard_PartyPoseUI/Blizzard_PartyPoseUI.xml#L90)
--- Template
--- @class PartyPoseFrameTemplate : Frame
--- @field Border PartyPoseFrameTemplate_Border
--- @field Background Texture
--- @field TitleBg Texture
--- @field TitleText PartyPoseFrameTemplate_TitleText

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/ptr/Interface/AddOns/Blizzard_PartyPoseUI/Blizzard_PartyPoseUI.xml#L165)
--- Template
--- @class PartyPoseModelFrameTemplate : ModelScene, NonInteractableModelSceneMixinTemplate
--- @field Bg Texture
--- @field ShadowCornerTopLeft Texture
--- @field ShadowCornerTopRight Texture
--- @field ShadowCornerBottomLeft Texture
--- @field ShadowCornerBottomRight Texture
--- @field ShadowCornerTop Texture
--- @field ShadowCornerLeft Texture
--- @field ShadowCornerRight Texture
--- @field ShadowCornerBottom Texture
--- @field OverlayShadowTopLeft Texture
--- @field OverlayShadowTopRight Texture
--- @field OverlayShadowBottomLeft Texture
--- @field OverlayShadowBottomRight Texture
--- @field OverlayShadowTop Texture
--- @field OverlayShadowLeft Texture
--- @field OverlayShadowRight Texture
--- @field OverlayShadowBottom Texture
--- @field InsetBorderTopLeft PartyPoseModelFrameTemplate_InsetBorderTopLeft
--- @field InsetBorderTopRight PartyPoseModelFrameTemplate_InsetBorderTopRight
--- @field InsetBorderBottomLeft PartyPoseModelFrameTemplate_InsetBorderBottomLeft
--- @field InsetBorderBottomRight PartyPoseModelFrameTemplate_InsetBorderBottomRight
--- @field InsetBorderTop PartyPoseModelFrameTemplate_InsetBorderTop
--- @field InsetBorderBottom PartyPoseModelFrameTemplate_InsetBorderBottom
--- @field InsetBorderLeft PartyPoseModelFrameTemplate_InsetBorderLeft
--- @field InsetBorderRight PartyPoseModelFrameTemplate_InsetBorderRight

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/ptr/Interface/AddOns/Blizzard_PartyPoseUI/Blizzard_PartyPoseUI.xml#L351)
--- Template
--- @class PartyPoseModelShadowTextureTemplate : Texture

