--- @meta _

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/ptr2/Interface/AddOns/Blizzard_Soulbinds/Blizzard_SoulbindsNode.xml#L5)
--- Template
--- @class SoulbindTreeNodeTemplate : Button, SoulbindTreeNodeMixin
--- @field FxModelScene SoulbindTreeNodeTemplate_FxModelScene
--- @field Arrow Texture
--- @field Arrow2 Texture

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/ptr2/Interface/AddOns/Blizzard_Soulbinds/Blizzard_SoulbindsNode.xml#L37)
--- Template
--- @class SoulbindTraitNodeTemplate : Button, SoulbindTreeNodeTemplate, SoulbindTraitNodeMixin
--- @field Background Texture
--- @field Icon Texture
--- @field IconOverlay Texture
--- @field Ring Texture
--- @field RingOverlay SoulbindTraitNodeTemplate_RingOverlay
--- @field MouseOverlay Texture

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/ptr2/Interface/AddOns/Blizzard_Soulbinds/Blizzard_SoulbindsNode.xml#L105)
--- Template
--- @class ConduitInstallTemplate : Texture

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/ptr2/Interface/AddOns/Blizzard_Soulbinds/Blizzard_SoulbindsNode.xml#L112)
--- Template
--- @class SoulbindConduitNodeTemplate : Button, SoulbindTreeNodeTemplate, SoulbindConduitNodeMixin
--- @field Background Texture
--- @field Icon Texture
--- @field IconOverlay Texture
--- @field Ring Texture
--- @field PickupOverlay SoulbindConduitNodeTemplate_PickupOverlay
--- @field PickupOverlay2 SoulbindConduitNodeTemplate_PickupOverlay2
--- @field PickupArrowsOverlay SoulbindConduitNodeTemplate_PickupArrowsOverlay
--- @field PickupArrowsStatic Texture
--- @field UnsocketedWarning SoulbindConduitNodeTemplate_UnsocketedWarning
--- @field UnsocketedWarning2 SoulbindConduitNodeTemplate_UnsocketedWarning2
--- @field EnhancedNodeSheen SoulbindConduitNodeTemplate_EnhancedNodeSheen
--- @field RingOverlay SoulbindConduitNodeTemplate_RingOverlay
--- @field MouseOverlay Texture
--- @field EmblemBg Texture
--- @field Ring2 SoulbindConduitNodeTemplate_Ring2
--- @field Ring3 SoulbindConduitNodeTemplate_Ring3
--- @field Ring4 SoulbindConduitNodeTemplate_Ring4
--- @field Ring5 SoulbindConduitNodeTemplate_Ring5
--- @field Ring6 SoulbindConduitNodeTemplate_Ring6
--- @field Ring7 SoulbindConduitNodeTemplate_Ring7
--- @field Pending Texture
--- @field PendingStick SoulbindConduitNodeTemplate_PendingStick
--- @field PendingStick2 SoulbindConduitNodeTemplate_PendingStick2
--- @field Emblem Texture

