--- @meta _

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/ptr/Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeSchematicForm.xml#L5)
--- Template
--- @class ProfessionsRecipeFormStarTemplate : Frame
--- @field Unearned Texture
--- @field Earned Texture
--- @field Flash Texture
--- @field Pulse ProfessionsRecipeFormStarTemplate_Pulse

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/ptr/Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeSchematicForm.xml#L25)
--- Template
--- @class ProfessionsRecipeSchematicFormTemplate : Frame, ProfessionsRecipeSchematicFormMixin
--- @field canShowFavoriteButton boolean # true
--- @field OutputIcon ProfessionsRecipeSchematicFormTemplate_OutputIcon
--- @field FavoriteButton ProfessionsRecipeSchematicFormTemplate_FavoriteButton
--- @field QualityDialog ProfessionsRecipeSchematicFormTemplate_QualityDialog
--- @field TrackRecipeCheckbox ProfessionsRecipeSchematicFormTemplate_TrackRecipeCheckbox
--- @field AllocateBestQualityCheckbox ProfessionsRecipeSchematicFormTemplate_AllocateBestQualityCheckbox
--- @field Reagents ProfessionsRecipeSchematicFormTemplate_Reagents
--- @field OptionalReagents ProfessionsRecipeSchematicFormTemplate_OptionalReagents
--- @field FinishingReagents ProfessionsRecipeSchematicFormTemplate_FinishingReagents
--- @field Concentrate ProfessionsRecipeSchematicFormTemplate_Concentrate
--- @field Stars ProfessionsRecipeSchematicFormTemplate_Stars
--- @field RecipeLevelBar ProfessionsRecipeSchematicFormTemplate_RecipeLevelBar
--- @field RecipeLevelDropdown ProfessionsRecipeSchematicFormTemplate_RecipeLevelDropdown
--- @field Details ProfessionsRecipeSchematicFormTemplate_Details
--- @field RecipeSourceButton ProfessionsRecipeSchematicFormTemplate_RecipeSourceButton
--- @field FirstCraftBonus ProfessionsRecipeSchematicFormTemplate_FirstCraftBonus
--- @field OutputText ProfessionsRecipeSchematicFormTemplate_OutputText
--- @field RecraftingOutputText ProfessionsRecipeSchematicFormTemplate_RecraftingOutputText
--- @field RecraftingDescription ProfessionsRecipeSchematicFormTemplate_RecraftingDescription
--- @field OutputSubText ProfessionsRecipeSchematicFormTemplate_OutputSubText
--- @field RequiredTools ProfessionsRecipeSchematicFormTemplate_RequiredTools
--- @field RecraftingRequiredTools ProfessionsRecipeSchematicFormTemplate_RecraftingRequiredTools
--- @field Cooldown ProfessionsRecipeSchematicFormTemplate_Cooldown
--- @field MinimizedCooldown ProfessionsRecipeSchematicFormTemplate_MinimizedCooldown
--- @field Description ProfessionsRecipeSchematicFormTemplate_Description

