--- @meta _

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/ptr/Interface/AddOns/Blizzard_FrameXML/ItemDisplay.xml#L5)
--- Template
--- @class LootItemExtended : Button, LootItemExtendedMixin
--- @field Icon Texture
--- @field IconBorder Texture
--- @field IconOverlay Texture
--- @field Count LootItemExtended_Count
--- @field IconOverlay2 Texture
--- @field SpecIcon Texture
--- @field SpecRing Texture
--- @field IconBorderDropShadow Texture
--- @field ItemBurst Texture
--- @field ItemBorderGlow Texture
--- @field GlowSmokeBurst Texture
--- @field Arrow1 LootItemExtended_Arrow1
--- @field Arrow2 LootItemExtended_Arrow2
--- @field Arrow3 LootItemExtended_Arrow3
--- @field Arrow4 LootItemExtended_Arrow4
--- @field Arrow5 LootItemExtended_Arrow5
--- @field animArrows LootItemExtended_animArrows
--- @field IconAnim LootItemExtended_IconAnim

