--- @meta _

--- [Source](https:/github.com/Gethe/wow-ui-source/blob/classic_era_ptr/Interface/AddOns/Blizzard_Communities/GuildRoster.xml#L5)
--- Template
--- @class CommunitiesGuildMemberDetailFrameTemplate : Frame, CommunitiesGuildMemberDetailMixin
--- @field Border CommunitiesGuildMemberDetailFrameTemplate_Border
--- @field CloseButton CommunitiesGuildMemberDetailFrameTemplate_CloseButton
--- @field RemoveButton CommunitiesGuildMemberDetailFrameTemplate_RemoveButton
--- @field GroupInviteButton CommunitiesGuildMemberDetailFrameTemplate_GroupInviteButton
--- @field RankDropdown CommunitiesGuildMemberDetailFrameTemplate_RankDropdown
--- @field NoteBackground CommunitiesGuildMemberDetailFrameTemplate_NoteBackground
--- @field OfficerNoteBackground CommunitiesGuildMemberDetailFrameTemplate_OfficerNoteBackground
--- @field Name CommunitiesGuildMemberDetailFrameTemplate_Name
--- @field Level CommunitiesGuildMemberDetailFrameTemplate_Level
--- @field ZoneLabel CommunitiesGuildMemberDetailFrameTemplate_ZoneLabel
--- @field ZoneText CommunitiesGuildMemberDetailFrameTemplate_ZoneText
--- @field RankLabel CommunitiesGuildMemberDetailFrameTemplate_RankLabel
--- @field RankText CommunitiesGuildMemberDetailFrameTemplate_RankText
--- @field OnlineLabel CommunitiesGuildMemberDetailFrameTemplate_OnlineLabel
--- @field OnlineText CommunitiesGuildMemberDetailFrameTemplate_OnlineText
--- @field NoteLabel CommunitiesGuildMemberDetailFrameTemplate_NoteLabel
--- @field OfficerNoteLabel CommunitiesGuildMemberDetailFrameTemplate_OfficerNoteLabel

