name: beta

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  beta:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: beta
      FLAVOR: mainline

  beta-mix-into-source:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: beta
      FLAVOR: mainline
      TARGET_BRANCH_SUFFIX: '-mix-into-source'
      MIX_ANNOTATIONS_INTO_SOURCE: true
      INCLUDE_RAW_XML_SOURCE: true
