name: classic_beta

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  classic_beta:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: classic_beta
      FLAVOR: mists

  classic_beta-mix-into-source:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: classic_beta
      FLAVOR: mists
      TARGET_BRANCH_SUFFIX: '-mix-into-source'
      MIX_ANNOTATIONS_INTO_SOURCE: true
      INCLUDE_RAW_XML_SOURCE: true
