name: classic_ptr

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  classic_ptr:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: classic_ptr
      FLAVOR: cata

  classic_ptr-mix-into-source:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: classic_ptr
      FLAVOR: cata
      TARGET_BRANCH_SUFFIX: '-mix-into-source'
      MIX_ANNOTATIONS_INTO_SOURCE: true
      INCLUDE_RAW_XML_SOURCE: true
