name: classic_era

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  classic_era:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: classic_era
      FLAVOR: vanilla

  classic_era-mix-into-source:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: classic_era
      FLAVOR: vanilla
      TARGET_BRANCH_SUFFIX: '-mix-into-source'
      MIX_ANNOTATIONS_INTO_SOURCE: true
      INCLUDE_RAW_XML_SOURCE: true
