name: force update all

on:
  workflow_dispatch:

jobs:
  live:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: live
      FLAVOR: mainline
      FORCE_UPDATE: true

  live-mix-into-source:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: live
      FLAVOR: mainline
      FORCE_UPDATE: true
      TARGET_BRANCH_SUFFIX: '-mix-into-source'
      MIX_ANNOTATIONS_INTO_SOURCE: true
      INCLUDE_RAW_XML_SOURCE: true

  ptr:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: ptr
      FLAVOR: mainline
      FORCE_UPDATE: true

  ptr-mix-into-source:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: ptr
      FLAVOR: mainline
      TARGET_BRANCH_SUFFIX: '-mix-into-source'
      MIX_ANNOTATIONS_INTO_SOURCE: true
      INCLUDE_RAW_XML_SOURCE: true
      FORCE_UPDATE: true

  ptr2:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: ptr2
      FLAVOR: mainline
      FORCE_UPDATE: true

  ptr2-mix-into-source:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: ptr2
      FLAVOR: mainline
      TARGET_BRANCH_SUFFIX: '-mix-into-source'
      MIX_ANNOTATIONS_INTO_SOURCE: true
      INCLUDE_RAW_XML_SOURCE: true
      FORCE_UPDATE: true

  beta:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: beta
      FLAVOR: mainline
      FORCE_UPDATE: true

  beta-mix-into-source:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: beta
      FLAVOR: mainline
      TARGET_BRANCH_SUFFIX: '-mix-into-source'
      MIX_ANNOTATIONS_INTO_SOURCE: true
      INCLUDE_RAW_XML_SOURCE: true
      FORCE_UPDATE: true

  classic:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: classic
      FLAVOR: cata
      FORCE_UPDATE: true

  classic-mix-into-source:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: classic
      FLAVOR: cata
      TARGET_BRANCH_SUFFIX: '-mix-into-source'
      MIX_ANNOTATIONS_INTO_SOURCE: true
      INCLUDE_RAW_XML_SOURCE: true
      FORCE_UPDATE: true

  classic_ptr:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: classic_ptr
      FLAVOR: cata
      FORCE_UPDATE: true

  classic_ptr-mix-into-source:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: classic_ptr
      FLAVOR: cata
      TARGET_BRANCH_SUFFIX: '-mix-into-source'
      MIX_ANNOTATIONS_INTO_SOURCE: true
      INCLUDE_RAW_XML_SOURCE: true
      FORCE_UPDATE: true

  classic_beta:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: classic_beta
      FLAVOR: mists
      FORCE_UPDATE: true

  classic_beta-mix-into-source:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: classic_beta
      FLAVOR: mists
      TARGET_BRANCH_SUFFIX: '-mix-into-source'
      MIX_ANNOTATIONS_INTO_SOURCE: true
      INCLUDE_RAW_XML_SOURCE: true
      FORCE_UPDATE: true

  classic_era:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: classic_era
      FLAVOR: vanilla
      FORCE_UPDATE: true

  classic_era-mix-into-source:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: classic_era
      FLAVOR: vanilla
      TARGET_BRANCH_SUFFIX: '-mix-into-source'
      MIX_ANNOTATIONS_INTO_SOURCE: true
      INCLUDE_RAW_XML_SOURCE: true
      FORCE_UPDATE: true

  classic_era_ptr:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: classic_era_ptr
      FLAVOR: vanilla
      FORCE_UPDATE: true

  classic_era_ptr-mix-into-source:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: classic_era_ptr
      FLAVOR: vanilla
      TARGET_BRANCH_SUFFIX: '-mix-into-source'
      MIX_ANNOTATIONS_INTO_SOURCE: true
      INCLUDE_RAW_XML_SOURCE: true
      FORCE_UPDATE: true
