name: live

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  live:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: live
      FLAVOR: mainline

  live-mix-into-source:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: live
      TARGET_BRANCH_SUFFIX: '-mix-into-source'
      FLAVOR: mainline
      MIX_ANNOTATIONS_INTO_SOURCE: true
      INCLUDE_RAW_XML_SOURCE: true
