name: ptr2

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  ptr2:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: ptr2
      FLAVOR: mainline

  ptr2-mix-into-source:
    uses: ./.github/workflows/template.yml
    with:
      BRANCH: ptr2
      FLAVOR: mainline
      TARGET_BRANCH_SUFFIX: '-mix-into-source'
      MIX_ANNOTATIONS_INTO_SOURCE: true
      INCLUDE_RAW_XML_SOURCE: true
